baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Math Tree'
theme = 'paper'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)']]
[params]
  math = true
